name: Primeiro Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Executando um comando
        run: echo Hello, world! 

      - name: Executando 2 comandos
        run: |
          echo Comando 1 executado,
          echo comando 2 tambem executa.
  deploy:
    needs: build
    runs-on: ubuntu-lasted
    
    steps:
      - uses: actions/checkout@v3

      - name: Publicando na Cloud
        run: echo Fazer deploy no Docker hub
    
